BIO:
   learning_rate: 0.001
   num_hidden: 512
   num_proj_hidden: 512
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.4
   drop_feature_rate_1: 0.1
   drop_feature_rate_2: 0.0
   tau: 0.7
   num_epochs: 2000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 2